apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: kube-quest
data:
  APP_NAME: {{ .Values.app.name }}
  APP_ENV: {{ .Values.app.env }}
  APP_DEBUG: {{ .Values.app.debug | quote }}
  APP_URL: {{ .Values.app.url }}
  DB_CONNECTION: pgsql
  DB_HOST: {{ .Release.Name }}-postgresql
  DB_PORT: "5432"
  DB_DATABASE: {{ .Values.postgresql.auth.database }}
  DB_USERNAME: {{ .Values.postgresql.auth.username }}
