apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: kube-quest
type: Opaque
stringData:
  APP_KEY: {{ .Values.app.key }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password }}
